# Generated by Django 5.2.8 on 2025-11-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sachuqari', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='image_paths',
        ),
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='orders/'),
        ),
    ]
