# Generated by Django 5.2.8 on 2025-11-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sachuqari', '0006_rename_gmail_order_gmail_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
