# Generated by Django 5.2.8 on 2025-11-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sachuqari', '0007_alter_order_delivery_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='num_people',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='video_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
