# Generated by Django 5.2.8 on 2025-11-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sachuqari', '0008_alter_child_name_alter_order_delivery_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_comment',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
